# utils/locales/ar.py

# Arabic Translations
translations = {
    "app_title": "نظام إدارة الموارد البشرية",
    "login_title": "تسجيل الدخول - نظام إدارة الموارد البشرية",
    "username_label": "اسم المستخدم:",
    "password_label": "كلمة المرور:",
    "login_btn": "تسجيل الدخول",
    "login_failed_title": "فشل تسجيل الدخول",
    "login_failed_message": "اسم المستخدم أو كلمة المرور غير صالحة.",
    "login_required_message": "اسم المستخدم وكلمة المرور مطلوبان.",
    "toggle_language_btn": "تغيير إلى الإنجليزية",
    "employee_id_label": "المعرف:",
    "name_label": "الاسم:",
    "department_label": "القسم:",
    "position_label": "المنصب:",
    "salary_label": "الراتب:",
    "add_employee_btn": "إضافة موظف",
    "update_selected_btn": "تحديث المحدد",
    "clear_fields_btn": "مسح الحقول والاختيار",
    "delete_selected_btn": "حذف المحدد",
    "refresh_list_btn_text": "تحديث القائمة", # New key
    "status_select_employee": "الحالة: اختر موظفًا",
    "initial_setup_title": "الإعداد الأولي",
    "initial_setup_message": "لم يتم العثور على مسؤول. يرجى إنشاء واحد.",
    "admin_setup_username_prompt": "أدخل اسم مستخدم المسؤول:",
    "admin_setup_password_prompt": "أدخل كلمة مرور المسؤول:",
    "setup_complete_title": "اكتمل الإعداد",
    "setup_complete_message": "تم إنشاء مستخدم المسؤول بنجاح. يرجى تسجيل الدخول.",
    "confirm_delete_title": "تأكيد الحذف",
    "confirm_delete_employee_message": "هل أنت متأكد أنك تريد حذف الموظف {emp_id}؟",
    "success_title": "نجاح",
    "employee_deleted_message": "تم حذف الموظف {emp_id} بنجاح.",
    "input_error_title": "خطأ في الإدخال",
    "db_error_title": "خطأ في قاعدة البيانات",
    "employee_added_message": "تمت إضافة الموظف {name} (المعرف: {emp_id}) بنجاح.",
    "required_fields_message": "الاسم والمنصب والراتب وأيام الإجازة مطلوبة.",
    "salary_negative_error": "لا يمكن أن يكون الراتب سالبًا.",
    "vacation_negative_error": "لا يمكن أن تكون أيام الإجازة سالبة.",
    # New keys for HRAppGUI (Arabic) - ensure all keys from 'en' are here
    "nav_employees_btn_text": "الموظفون",
    "nav_adv_search_btn_text": "بحث متقدم",
    "nav_dashboard_btn_text": "لوحة التحكم",
    "nav_reports_btn_text": "التقارير",
    "nav_payroll_btn_text": "كشوف المرتبات",
    "nav_alerts_btn_text": "التنبيهات",
    "nav_analytics_btn_text": "التحليلات",
    "nav_user_admin_btn_text": "إدارة المستخدمين",
    "nav_settings_btn_text": "الإعدادات",
    "nav_device_sync_btn_text": "مزامنة الجهاز",
    "toggle_dark_mode_btn_text": "تبديل الوضع الداكن",
    "toggle_light_mode_btn_text": "تبديل الوضع الفاتح",
    "search_filter_frame_title": "بحث وتصفية",
    "search_field_label": "الحقل:",
    "search_term_label": "مصطلح البحث:",
    "search_button_text": "بحث",
    "show_all_button_text": "عرض الكل",
    "employee_list_frame_title": "قائمة الموظفين",
    "employee_actions_table_frame_title": "إجراءات الموظفين (جدول)",
    "selected_employee_actions_frame_title": "إجراءات الموظف المحدد",
    "view_full_profile_btn_text": "عرض الملف الشخصي الكامل",
    "print_btn_text": "طباعة",
    "terminate_employee_btn_text": "إنهاء خدمة الموظف",
    "export_csv_btn_text": "تصدير CSV",
    "import_csv_btn_text": "استيراد CSV",
    "clock_in_selected_btn_text": "تسجيل حضور المحدد",
    "clock_out_selected_btn_text": "تسجيل انصراف المحدد",
    "view_attendance_log_btn_text": "عرض سجل الحضور",
    "status_bar_ready_text": "الحالة: جاهز",
    "start_date_required_error": "تاريخ البدء مطلوب.",
    "invalid_salary_vacation_format": "تنسيق غير صالح للراتب (رقم) أو أيام الإجازة (عدد صحيح).",
    "employee_updated_message": "تم تحديث الموظف (المعرف: {emp_id}) بنجاح.",
    "no_employee_selected_error": "لم يتم تحديد موظف أو حقل المعرف فارغ. يرجى تحديد موظف من القائمة أو البحث.",
    # About Dialog (Arabic)
    "about_dialog_title": "حول نظام إدارة الموارد البشرية",
    "about_program_name_label": "اسم البرنامج:",
    "about_version_label": "الإصدار:",
    "about_developer_label": "المطور:",
    "about_copyright_label": "حقوق النشر:",
    "about_close_btn": "إغلاق",
    # User Admin (Arabic)
    "user_admin_username_label": "اسم المستخدم:",
    "user_admin_password_label": "كلمة المرور (اتركه فارغًا للإبقاء على الحالية):",
    "user_admin_password_hint": "(اتركه فارغًا للإبقاء على كلمة المرور الحالية)",
    "user_admin_role_label": "الدور:",
    "user_admin_add_btn": "إضافة مستخدم",
    "user_admin_save_changes_btn": "حفظ التغييرات", # Was "تحديث المستخدم"
    "user_admin_delete_btn": "حذف المستخدم",
    "user_admin_clear_btn": "مسح الحقول",
    "user_admin_list_frame_title": "قائمة المستخدمين",
    "user_admin_details_frame_title": "تفاصيل المستخدم / الإجراءات",
    # Employee Tasks (Arabic)
    "nav_employee_tasks_btn_text": "مهام الموظفين",
    "tasks_view_title": "إدارة مهام الموظفين",
    "tasks_filter_frame_title": "تصفية المهام",
    "tasks_assignee_label": "مُسندة إلى (موظف):",
    "tasks_status_label": "الحالة:",
    "tasks_priority_label": "الأولوية:",
    "tasks_assigned_by_label": "أُسندت بواسطة (مستخدم):",
    "tasks_monitor_label": "مُراقبة بواسطة (مستخدم):",
    "tasks_add_btn_text": "إضافة مهمة جديدة",
    "tasks_edit_btn_text": "تعديل المهمة المحددة",
    "tasks_delete_btn_text": "حذف المهمة المحددة",
    "tasks_refresh_btn_text": "تحديث القائمة",
    "task_form_title_add": "إضافة مهمة جديدة",
    "task_form_title_edit": "تعديل المهمة",
    "task_title_label": "عنوان المهمة:",
    "task_description_label": "الوصف:",
    "task_due_date_label": "تاريخ الاستحقاق:",
    "task_all_option": "الكل",
    # Dashboard 2.0 (Arabic)
    "dashboard_period_label": "اختر الفترة:",
    "dashboard_from_date_label": "من تاريخ:",
    "dashboard_to_date_label": "إلى تاريخ:",
    "dashboard_refresh_btn_text": "تحديث لوحة التحكم",
    "dashboard_chart_headcount_title": "عدد الموظفين حسب القسم",
    "dashboard_chart_absenteeism_title": "معدل الغياب حسب القسم (%)",
    "dashboard_chart_leave_status_title": "حالات طلبات الإجازة",
    "dashboard_chart_dept_adherence_title": "نسبة الالتزام بالحضور حسب القسم (%)",
    "dashboard_chart_payslips_title": "كشوف المرتبات الصادرة حسب القسم",
    "dashboard_card_employees": "إجمالي الموظفين",
    "dashboard_card_pending_leaves": "الإجازات المعلقة",
    "dashboard_card_departments": "الأقسام",
    "dashboard_card_absences_today": "غيابات اليوم", # Already correct
    "dashboard_card_absences_this_week": "غيابات هذا الأسبوع",
    "dashboard_card_absences_this_month": "غيابات هذا الشهر",
    "dashboard_card_absences_last_month": "غيابات الشهر الماضي",
    "dashboard_card_absences_this_year": "غيابات هذا العام",
    "dashboard_card_absences_last_year": "غيابات العام الماضي",
    "dashboard_card_payslips_generated": "كشوف المرتبات الصادرة",
    "dashboard_card_payslips_pending": "كشوف المرتبات المعلقة",
    "dashboard_card_payslips_overdue": "كشوف المرتبات المتأخرة",
    "dashboard_card_employee_turnover": "دوران الموظفين",
    "dashboard_card_employee_turnover_rate": "معدل دوران الموظفين (%)",
    "dashboard_card_avg_working_hours": "متوسط ساعات العمل",
    "dashboard_card_avg_leave_days": "متوسط أيام الإجازة",
    "dashboard_card_avg_vacation_days": "متوسط أيام العطلة",
    "dashboard_card_avg_salary": "متوسط الراتب",
    "dashboard_card_avg_leave_requests": "متوسط طلبات الإجازة",
    "dashboard_card_avg_payslips": "متوسط كشوف المرتبات الصادرة",
    "dashboard_card_avg_absences": "متوسط الغيابات",
    "dashboard_card_avg_payroll": "متوسط الرواتب",
    "dashboard_card_avg_turnover": "متوسط دوران الموظفين",
    # Removed duplicated dashboard_card_avg_... keys
    # Removed dashboard_chart_absences, dashboard_chart_leave_status etc. as they are covered by specific titles
    "dashboard_no_data_for_charts": "لا توجد بيانات للرسوم البيانية في الفترة المحددة.",
    # Chatbot Assistant (Arabic)
    "adv_search_all_departments_option": "جميع الأقسام",
    "gender_option_all": "جميع الأجناس",
    "gender_option_male": "ذكر",
    "gender_option_female": "أنثى",
    "gender_option_other": "آخر",
    "nav_chatbot_btn_text": "المساعد",
    "chatbot_window_title": "المساعد الافتراضي للموارد البشرية",
    "chatbot_input_prompt": "اكتب أمرك أو سؤالك...",
    "chatbot_send_btn": "إرسال",
    "chatbot_greeting": "مرحباً! كيف يمكنني مساعدتك اليوم؟ اكتب 'مساعدة' للأوامر.",
    "chatbot_help_text": "الأوامر المتاحة:\n- 'مرحباً' أو 'أهلاً'\n- 'عرض موظف [المعرف]'\n- 'قائمة الموظفين'\n- 'مساعدة'",
    "chatbot_unknown_command": "عذراً، لم أفهم ذلك. اكتب 'مساعدة' للأوامر المتاحة.",
    # New keys from recent changes (Arabic)
    "stats_summary_frame_title": "ملخص الإحصائيات",
    "recommendations_alerts_frame_title": "التوصيات والتنبيهات",
    "device_sync_info_frame_title": "معلومات الجهاز",
    "device_sync_assoc_device_label": "الجهاز المرتبط:",
    "device_sync_last_sync_label": "آخر مزامنة:",
    "device_sync_status_label": "الحالة:",
    "device_sync_test_conn_btn": "اختبار الاتصال",
    "device_sync_resync_btn": "مزامنة الآن",
    "device_sync_auto_sync_toggle": "تمكين المزامنة التلقائية",
    "device_sync_log_frame_title": "سجل المزامنة",
    "interview_scheduling_placeholder_label": "إدارة جداول المقابلات",
    "interview_scheduling_open_window_btn": "فتح مجدول المقابلات",
    "metrics_placeholder_label": "عرض مقاييس الموارد البشرية والتطبيق",
    "metrics_open_window_btn": "فتح لوحة مقاييس الأداء",
    "metrics_dashboard_title": "مقاييس الموارد البشرية والتطبيق",
    "nav_metrics_btn_text": "المقاييس",
    "metrics_hr_tab_title": "مقاييس الموارد البشرية",
    "metrics_app_usage_tab_title": "استخدام التطبيق",
    "nav_interview_scheduling_btn_text": "جدولة المقابلات",

    # Tooltips (Arabic)
    "tooltip_add_employee": "فتح نموذج لإضافة موظف جديد (Ctrl+N).",
    "tooltip_refresh_list": "تحديث قائمة الموظفين من قاعدة البيانات.", # New key
    "tooltip_update_selected": "تحديث بيانات الموظف المحدد في قاعدة البيانات.",
    "tooltip_clear_fields": "مسح الحقول وإلغاء اختيار الموظف المحدد.",
    "tooltip_delete_selected": "حذف الموظف المحدد من قاعدة البيانات.",
    "tooltip_view_full_profile": "فتح عرض الملف الشخصي الكامل للموظف المحدد.",
    "tooltip_print": "طباعة بيانات الموظف المحدد.",
    "tooltip_terminate_employee": "إنهاء خدمة الموظف المحدد.",
    "tooltip_export_csv": "تصدير بيانات الموظفين إلى ملف CSV.",
    "tooltip_import_csv": "استيراد بيانات الموظفين من ملف CSV.",
    "tooltip_clock_in_selected": "تسجيل حضور الموظف المحدد.",
    "tooltip_clock_out_selected": "تسجيل انصراف الموظف المحدد.",
    "tooltip_view_attendance_log": "فتح نموذج سجل حضور الموظف المحدد.",
    "tooltip_view_manage_employees": "عرض وإدارة تفاصيل الموظفين.",
    "tooltip_adv_search_employees": "فتح البحث المتقدم عن الموظفين.",
    "tooltip_view_dashboard": "فتح لوحة تحكم الموارد البشرية.",
    "tooltip_generate_reports": "إنشاء تقارير موارد بشرية متنوعة.",
    "tooltip_manage_payroll": "الوصول إلى ميزات إدارة كشوف المرتبات.",
    "tooltip_view_hr_alerts": "عرض تنبيهات وإشعارات الموارد البشرية.",
    "tooltip_manage_tasks": "إدارة مهام الموظفين.",
    # "nav_interview_scheduling_btn_text" is already defined above
    "tooltip_manage_interviews": "إدارة جداول المقابلات.",
    "tooltip_access_analytics": "الوصول إلى ميزات التحليلات التنبؤية.",
    # "nav_metrics_btn_text" is already defined above
    "tooltip_view_metrics": "عرض مقاييس الموارد البشرية والتطبيق.",
    "tooltip_sync_device_data": "مزامنة البيانات مع أجهزة الحضور والانصراف.",
    "tooltip_manage_users": "إدارة مستخدمي التطبيق وأدوارهم.",
    "tooltip_configure_settings": "تكوين إعدادات التطبيق.",
    "tooltip_open_chatbot": "فتح المساعد الافتراضي للموارد البشرية.",
    "tooltip_show_about_program": "عرض معلومات حول البرنامج.",
    "tooltip_toggle_theme": "التبديل بين الوضع الفاتح والداكن.",
    # UI elements that need translation
    "main_tab_employees": "الموظفون",
    "main_tab_search": "بحث",
    # "main_tab_dashboard": "لوحة التحكم", # Removed
    # "main_tab_reports": "التقارير", # Removed
    # "main_tab_payroll": "كشوف المرتبات", # Removed
    "main_tab_alerts": "التنبيهات",
    "main_tab_analytics": "التحليلات",
    "main_tab_user_admin": "إدارة المستخدمين",
    "main_tab_settings": "الإعدادات",
    "main_tab_device_sync": "مزامنة الجهاز",
    "main_tab_tasks": "المهام",
    "main_tab_metrics": "المقاييس",
    "main_tab_interview_scheduling": "جدولة المقابلات",
    "emp_details_tab_general_info": "معلومات عامة", # This line is correct
    "emp_details_tab_attendance": "الحضور",
    "emp_details_tab_payroll": "سجل الرواتب",
    "emp_details_tab_documents": "المستندات",
    "emp_details_tab_action_log": "سجل الإجراءات",
    "job_details_section_title": "تفاصيل الوظيفة",
    "benefits_device_section_title": "المزايا والجهاز",
    "qualifications_history_section_title": "المؤهلات والتاريخ",
    "emp_hist_section_title": "📜 تاريخ التوظيف",
    "photo_section_title": "🖼️ الصورة",
    "no_photo_text": "لا توجد صورة",
    "marital_status_icon_label": "🎂 الحالة الاجتماعية:",
    "gender_icon_label": "🚻 الجنس:",
    "phone_icon_label": "☎ الهاتف:",
    "email_icon_label": "📧 البريد الإلكتروني:",
    "department_icon_label": "🏢 القسم:", "position_icon_label": "💼 المنصب:",
    "salary_icon_label": "💰 الراتب:",
    "start_date_icon_label": "📅 تاريخ البدء:",
    "status_icon_label": "🚦 الحالة:",
    "termination_date_icon_label": "🚪 تاريخ الإنهاء:",
    "vacation_days_icon_label": "🏖️ أيام الإجازة:",
    "exclude_vacation_policy_icon_label": "🚫 استثناء من سياسة الإجازات:",
    "device_user_id_icon_label": "🆔 معرف الجهاز:",
    "education_icon_label": "🎓 التعليم:",
    "dashboard_placeholder_label": "Dashboard content will be displayed here. Click button to open full dashboard.", # Placeholder
    "reports_placeholder_label": "Reports content will be displayed here. Click button to open reports window.", # Placeholder
    "payroll_placeholder_label": "Payroll content will be displayed here. Click button to open payroll window.", # Placeholder
    "alerts_placeholder_label": "Alerts content will be displayed here. Click button to open alerts window.", # Placeholder
    "settings_placeholder_label": "Settings content will be displayed here. Click button to open settings window.", # Placeholder
    "analytics_placeholder_title": "Predictive Analytics (Experimental)", # Placeholder
    "analytics_train_attrition_btn": "Train Employee Attrition Model", # Placeholder
    "analytics_attrition_placeholder_text": "Attrition model status and predictions will appear here...", # Placeholder
    "profile_window_title_prefix": "الملف الشخصي",
    "profile_tab_details": "التفاصيل الشخصية والوظيفية",
    "profile_tab_documents": "المستندات",
    "profile_tab_action_log": "سجل الإجراءات",
    "profile_tab_econtract": "العقد الإلكتروني",
    "profile_tab_cv_analysis": "تحليل السيرة الذاتية والملاءمة",
    "profile_section_personal_info": "👤 المعلومات الشخصية",
    "profile_section_contact_info": "📞 معلومات الاتصال",
    "profile_section_employment_details": "💼 تفاصيل التوظيف",
    "profile_section_system_benefits": "⚙️ النظام والمزايا",
    "profile_section_qualifications": "🎓 المؤهلات",
    "profile_section_photo": "🖼️ الصورة الشخصية",
    "profile_no_photo_text": "لا توجد صورة متاحة",
    "profile_section_emp_history": "📜 تاريخ التوظيف",
    "profile_doc_section_title": "المستندات",
    "profile_doc_view_btn": "عرض المحدد",
    "profile_doc_delete_btn": "حذف المحدد",
    "profile_doc_add_btn": "إضافة مستند",
    "profile_doc_sign_btn": "توقيع المستند",
    "profile_doc_create_contract_btn": "إنشاء عقد جديد",
    "profile_doc_id_header": "معرف المستند",
    "profile_doc_type_header": "النوع",
    "profile_doc_filename_header": "اسم الملف",
    "profile_doc_uploaded_header": "تاريخ الرفع",
    "profile_action_log_section_title": "سجل إجراءات الموظف",
    "profile_action_log_timestamp_header": "الطابع الزمني",
    "profile_action_log_action_header": "وصف الإجراء",
    "profile_action_log_performed_by_header": "تم بواسطة",
    "profile_econtract_section_title": "إدارة العقود الإلكترونية لهذا الموظف",
    "profile_econtract_manage_btn": "إنشاء/إدارة العقود",
    "profile_cv_upload_section_title": "رفع وتحليل السيرة الذاتية",
    "profile_cv_file_label": "ملف السيرة الذاتية:",
    "profile_cv_browse_btn": "تصفح...",
    "profile_cv_parse_btn": "تحليل السيرة الذاتية",
    "profile_cv_extracted_data_section_title": "البيانات المستخرجة من السيرة الذاتية",
    "profile_cv_parsed_data_placeholder": "ستظهر بيانات السيرة الذاتية المحللة هنا...",
    "profile_cv_suitability_section_title": "تقييم الملاءمة الأساسي",
    "profile_cv_job_desc_label": "الوصف الوظيفي/الكلمات المفتاحية:",
    "profile_cv_job_desc_placeholder": "ألصق الوصف الوظيفي أو الكلمات المفتاحية المطلوبة هنا (مفصولة بفواصل للكلمات المفتاحية).",
    "profile_cv_assess_btn": "تقييم الملاءمة",
    "profile_cv_suitability_results_placeholder": "ستظهر نتائج تقييم الملاءمة هنا...",
    "about_tech_support_header": "الدعم الفني",
    "about_support_email_label": "البريد الإلكتروني للدعم:",
    "about_support_phone_label": "الهاتف / واتساب:",
    # EmployeeFormWindow (Arabic)
    "form_window_title_add": "إضافة موظف جديد",
    "form_window_title_edit": "تعديل الموظف: {emp_id}",
    "form_section_personal_photo": "المعلومات الشخصية والصورة",
    "form_marital_status_label": "🎂 الحالة الاجتماعية:", # Reuses marital_status_icon_label
    "form_gender_label": "🚻 الجنس:", # Reuses gender_icon_label
    "form_photo_path_label": "🖼️ مسار الصورة:",
    "form_section_contact_info": "معلومات الاتصال", # Reuses profile_section_contact_info
    "form_phone_label": "☎ الهاتف:", # Reuses phone_icon_label
    "form_email_label": "📧 البريد الإلكتروني:", # Reuses email_icon_label
    "form_section_employment_details": "تفاصيل التوظيف", # Reuses profile_section_employment_details
    "form_section_benefits_device": "المزايا ومعرف الجهاز", # Similar to benefits_device_section_title
    "form_vacation_days_label": "🏖️ أيام الإجازة:", # Reuses vacation_days_icon_label
    "form_exclude_vacation_label": "🚫 استثناء من سياسة الإجازات:", # Reuses exclude_vacation_policy_icon_label
    "form_device_id_label": "🆔 معرف الجهاز:", # Reuses device_user_id_icon_label
    "form_section_qualifications_history": "المؤهلات والتاريخ", # Reuses qualifications_history_section_title
    "form_education_label": "🎓 التعليم:", # Reuses education_icon_label
    "form_emp_history_label": "📜 تاريخ التوظيف:", # Reuses emp_hist_section_title
    "form_button_cancel": "إلغاء",
    "form_button_clear_fields": "مسح الحقول",
    "form_button_save": "حفظ",
    "form_photo_preview_text": "معاينة الصورة",
    "form_browse_btn": "تصفح...", # Reuses profile_cv_browse_btn
    "form_clear_btn": "مسح", # Generic clear
    "form_tooltip_salary": "أدخل الراتب الشهري الإجمالي للموظف.",
    "form_tooltip_photo_path": "مسار ملف صورة الموظف (JPG, PNG, إلخ).",
    "form_tooltip_photo_browse": "تصفح بحثًا عن ملف صورة.",
    "form_tooltip_phone": "أدخل رقم هاتف الموظف.",
    "form_tooltip_email": "أدخل عنوان البريد الإلكتروني للموظف.",
    "form_tooltip_photo_clear": "مسح مسار الصورة المحدد.",
    "form_tooltip_save_add": "حفظ سجل الموظف الجديد.",
    "form_tooltip_save_edit": "حفظ التغييرات في سجل الموظف.",
    "form_tooltip_clear_form": "إعادة تعيين جميع الحقول في النموذج.",
    "form_tooltip_cancel_form": "إغلاق هذا النموذج دون حفظ.",
    # AppSettingsWindow (Arabic)
    "settings_window_title": "إعدادات التطبيق",
    "settings_group_cloud_backup": "☁️ النسخ الاحتياطي السحابي (Google Drive)",
    "settings_gdrive_status_label": "الحالة:",
    "settings_gdrive_auth_button_text": "المصادقة مع Google Drive",
    "settings_gdrive_backup_now_button_text": "النسخ الاحتياطي والمزامنة إلى Drive الآن",
    "settings_group_general_appearance": "⚙️ عام والمظهر",
    "settings_default_lang_label": "اللغة الافتراضية:",
    "settings_default_theme_label": "السمة الافتراضية:",
    "settings_group_telegram": "📲 إشعارات Telegram",
    "settings_telegram_token_label": "رمز Telegram Bot:",
    "settings_telegram_chat_id_label": "معرف دردشة Telegram:",
    "settings_group_zkteco": "🔗 جهاز ZKTeco",
    "settings_zkteco_ip_label": "IP جهاز ZKTeco:",
    "settings_zkteco_port_label": "منفذ جهاز ZKTeco:",
    "settings_group_backup_recovery": "💾 النسخ الاحتياطي والاسترداد",
    "settings_auto_backup_label": "تمكين النسخ الاحتياطي التلقائي:",
    "settings_auto_backup_freq_label": "تكرار النسخ الاحتياطي التلقائي:",
    "settings_group_data_management": "🧹 إدارة البيانات",
    "settings_archive_cutoff_label": "أرشفة الموظفين المنتهية خدمتهم قبل:",
    "settings_archive_button_text": "أرشفة الآن",
    "settings_group_policies_rules": "📜 السياسات والقواعد",
    "settings_leave_busy_threshold_label": "عتبة انشغال الإجازة (٪ قسم):",
    "settings_public_holidays_label": "العطل الرسمية (YYYY-MM-DD، مفصولة بفواصل):",
    "settings_late_arrival_time_label": "وقت إشعار الوصول المتأخر (HH:MM:SS):",
    "settings_group_auto_reports": "📊 التقارير التلقائية",
    "settings_enable_weekly_stats_label": "تمكين تقرير الإحصاءات الأسبوعية:",
    "settings_report_day_label": "يوم التقرير:",
    "settings_report_time_label": "وقت التقرير (HH:MM):",
    "settings_button_save": "حفظ الإعدادات",
    "settings_saved_title": "تم حفظ الإعدادات",
    "settings_saved_success_message": "تم حفظ الإعدادات بنجاح.",
    "failed_to_save_settings_error": "فشل حفظ الإعدادات: {error}",
    "language_change_title": "تغيير اللغة",
    "settings_button_close": "إغلاق", # Reuses about_close_btn
    # PayrollWindow (Arabic)
    "payroll_window_title": "إدارة الرواتب",
    "payroll_tab_generate": "إنشاء قسيمة راتب",
    "payroll_tab_advances": "سلف الرواتب",
    "payroll_tab_rewards_penalties": "المكافآت والعقوبات",
    "payroll_employee_label": "الموظف:",
    "payroll_period_start_label": "بداية الفترة (YYYY-MM-DD):",
    "payroll_period_end_label": "نهاية الفترة (YYYY-MM-DD):",
    "payroll_calculate_button": "حساب قسيمة الراتب",
    "payroll_payslip_details_label": "تفاصيل قسيمة الراتب",
    "payroll_save_button": "حفظ قسيمة الراتب",
    "payroll_export_pdf_button": "تصدير PDF",
    "payroll_rp_form_title": "إضافة مكافأة أو عقوبة",
    "payroll_rp_type_label": "النوع:",
    "payroll_rp_reward_radio": "مكافأة",
    "payroll_rp_penalty_radio": "عقوبة",
    "payroll_rp_description_label": "الوصف:",
    "payroll_rp_amount_label": "المبلغ:",
    "payroll_rp_eff_date_label": "تاريخ السريان (YYYY-MM-DD):",
    "payroll_rp_add_item_button": "إضافة بند",
    "payroll_adv_form_title": "إضافة سلفة راتب جديدة",
    "payroll_adv_date_label": "تاريخ السلفة (YYYY-MM-DD):",
    "payroll_adv_amount_label": "مبلغ السلفة:",
    "payroll_adv_repay_per_period_label": "السداد/الفترة:",
    "payroll_adv_repay_start_date_label": "بداية السداد (YYYY-MM-DD):",
    "payroll_adv_add_button": "إضافة سلفة راتب",
    # Interview Scheduling (Arabic)
    "interview_form_frame_title": "جدولة/تعديل المقابلة",
    "candidate_name_label": "اسم المرشح:",
    "interviewer_label": "المُحاوِر:",
    "date_label_format": "التاريخ (YYYY-MM-DD):",
    "time_label_format": "الوقت (HH:MM):",
    "duration_minutes_label": "المدة (دقائق):",
    "location_label": "الموقع:",
    "status_label": "الحالة:",
    "notes_label": "ملاحظات:",
    "interview_schedule_button": "جدولة المقابلة",
    "interview_clear_form_button": "مسح النموذج",
    "interview_list_frame_title": "المقابلات المجدولة",
    # Employee Details Tab (General Info Section Titles) - Arabic
    "personal_info_section_title": "المعلومات الشخصية", # Used for multiple LabelFrames
    # Placeholder button texts for opening windows from main tabs - Arabic
    "dashboard_open_window_btn": "فتح لوحة التحكم الكاملة",
    "reports_open_window_btn": "فتح نافذة التقارير",
    "payroll_open_window_btn": "فتح نافذة الرواتب",
    "alerts_open_window_btn": "فتح نافذة التنبيهات",
    "settings_open_window_btn": "فتح نافذة الإعدادات",
    # Main Employee List Treeview Headers - Arabic
    "header_emp_id": "المعرف",
    "header_emp_name": "الاسم",
    "header_emp_department": "القسم",
    "header_emp_position": "المنصب",
    "header_emp_salary": "الراتب",
    "header_emp_status": "الحالة",
    "header_emp_termination_date": "تاريخ الإنهاء",
    "header_exclude_vacation_policy": "مستثنى من سياسة الإجازات",
    # ElectronicContractWindow
    "econtract_save_signed_btn": "حفظ العقد الموقع", # Keep existing
    "contract_pdf_generated_success_message": "تم إنشاء ملف PDF للعقد بنجاح: {filepath}",
    "signing_error_title": "خطأ في التوقيع",
    "create_contract_pdf_first_warning": "يرجى إنشاء ملف PDF للعقد أولاً.",
    "save_error_title": "خطأ في الحفظ",
    "save_error_title": "خطأ في الحفظ",
    "no_signed_contract_to_save_warning": "لا يوجد ملف PDF لعقد موقع متاح للحفظ. يرجى إنشاء العقد وتوقيعه أولاً.",
    # ReportsWindow specific for Performance Evaluation
    "report_type_perf_eval": "تقرير تقييم أداء الموظف",
    "report_select_employee_label": "اختر الموظف:",
    "report_eval_period_label": "فترة التقييم (مثال: YYYY-Q[1-4] أو 'الأحدث'):",
    "report_header_eval_period": "فترة التقييم",
    "report_header_eval_date": "تاريخ التقييم",
    "report_header_evaluator": "المُقيِّم",
    "report_header_criteria": "المعيار",
    "report_header_score": "الدرجة",
    "report_header_max_points": "الحد الأقصى",
    "report_header_comment": "تعليق",
    # Task Form
    "task_form_save_button": "حفظ المهمة",
    "unexpected_error_title": "خطأ غير متوقع",
    "unexpected_error_occurred_message": "حدث خطأ غير متوقع: {error}",
    "report_header_overall_score": "الدرجة الإجمالية",
    "no_signed_contract_to_save_warning": "لا يوجد ملف PDF لعقد موقع متاح للحفظ. يرجى إنشاء العقد وتوقيعه أولاً.",
    "report_header_overall_notes": "ملاحظات عامة",
    # Approvals Feature
    "main_tab_approvals": "الموافقات",
    "nav_approvals_btn_text": "الموافقات",
    "tooltip_manage_approvals": "عرض وإدارة العناصر المعلقة لموافقتك.",
    "pending_approvals_frame_title": "معلق لموافقتك",
    "approval_details_frame_title": "تفاصيل وإجراءات الموافقة",
    "approver_comments_label": "تعليقات الموافق:",
    "approve_btn_text": "موافقة",
    "reject_btn_text": "رفض",
    "contract_submitted_for_approval_message": "تم تقديم العقد للموافقة بنجاح.",
# AppSettingsWindow - GDrive (Arabic)
    "gdrive_status_not_authenticated": "الحالة: غير مصادق عليه. انقر للمصادقة.",
    "gdrive_status_authenticated": "الحالة: تمت المصادقة مع Google Drive.",
    "gdrive_status_auth_failed": "الحالة: فشلت المصادقة.",
    "gdrive_status_auth_error": "الحالة: خطأ في المصادقة.",
    "gdrive_authenticating_status": "جارٍ المصادقة... يرجى اتباع التعليمات في المتصفح.",
    "gdrive_credentials_not_found_error": "ملف بيانات اعتماد Google API ('{path}') غير موجود. لا يمكن المصادقة.",
    "gdrive_auth_failed_network_error": "فشلت المصادقة مع Google Drive بسبب مشكلة في الشبكة أو الإعداد: {error}",
    "gdrive_auth_failed_check_logs_message": "فشلت المصادقة مع Google Drive. يرجى مراجعة السجلات للحصول على التفاصيل.",
    # DashboardWindow Charts
    "dashboard_chart_headcount_title": "عدد الموظفين حسب القسم",
    "dashboard_chart_contract_type_title": "توزيع أنواع العقود",
    "dashboard_counter_total_employees": "إجمالي الموظفين النشطين:",
    "dashboard_counter_new_this_month": "الموظفون الجدد (هذا الشهر):",
    "dashboard_window_title": "لوحة تحكم الموارد البشرية",
    "dashboard_tab_employees": "الموظفون",
    "dashboard_tab_attendance": "الحضور",
    "dashboard_tab_payroll": "الرواتب",
    "dashboard_tab_performance": "الأداء",
    "dashboard_charts_section_title": "الرسوم البيانية",
    # DashboardWindow Cards (from error log)
    "Total Employees": "إجمالي الموظفين",
    "Pending Leaves": "الإجازات المعلقة",
    "Departments": "الأقسام",
    "reports_generation_error": "خطأ في إنشاء التقرير: {error_message}",
    "Absences Today": "غيابات اليوم", # Existing
    # Instant Status Assessment & Smart Alerts (Arabic)
    "status_checked_in": "تم تسجيل الحضور",
    "status_checked_out": "تم تسجيل الانصراف",
    "status_late": "متأخر",
    "header_emp_today_status": "حالة اليوم",
    "status_on_time": "في الوقت المحدد",
    "status_absent": "غائب",
    "status_lateness_detail": "{minutes} دقيقة تأخير",
    "settings_group_attendance_policy_alerts": "🕒 سياسة الحضور والتنبيهات",
    "settings_enable_instant_lateness_display_label": "تمكين عرض التأخير الفوري:",
    "settings_attendance_grace_period_label": "فترة السماح للحضور (دقائق):",
    "settings_enable_absence_alert_label": "تمكين تنبيه الغياب اليومي:",
    "settings_absence_alert_cutoff_time_label": "وقت قطع تنبيه الغياب (HH:MM):",
    "settings_absence_alert_telegram_chat_id_label": "معرف دردشة Telegram لتنبيه الغياب (اختياري):",
    "settings_enable_repeated_lateness_alert_label": "تمكين تنبيه التأخير المتكرر:",
    "settings_lateness_alert_threshold_count_label": "عدد مرات التأخير للتنبيه:",
    "settings_lateness_alert_period_days_label": "فترة تتبع التأخير (أيام):",
    "settings_repeated_lateness_alert_telegram_chat_id_label": "معرف دردشة Telegram لتنبيه التأخير المتكرر (اختياري):"
}