# utils/locales/en.py

# English Translations
translations = {
    "app_title": "HR Management System",
    "login_title": "Login - HR Management System",
    "username_label": "Username:",
    "password_label": "Password:",
    "login_btn": "Login",
    "login_failed_title": "Login Failed",
    "login_failed_message": "Invalid username or password.",
    "login_required_message": "Username and Password are required.",
    "toggle_language_btn": "تغيير إلى العربية", # "Change to Arabic"
    "employee_id_label": "ID:",
    "name_label": "Name:",
    "department_label": "Department:",
    "position_label": "Position:",
    "salary_label": "Salary:",
    "add_employee_btn": "Add Employee",
    "update_selected_btn": "Update Selected",
    "clear_fields_btn": "Clear Fields & Selection",
    "delete_selected_btn": "Delete Selected",
    "refresh_list_btn_text": "Refresh List", # New key
    "status_select_employee": "Status: Select an employee",
    "initial_setup_title": "Initial Setup",
    "initial_setup_message": "No admin user found. Please create one.",
    "admin_setup_username_prompt": "Enter Admin Username:",
    "admin_setup_password_prompt": "Enter Admin Password:",
    "setup_complete_title": "Setup Complete",
    "setup_complete_message": "Admin user created successfully. Please log in.",
    "confirm_delete_title": "Confirm Delete",
    "confirm_delete_employee_message": "Are you sure you want to delete employee {emp_id}?",
    "success_title": "Success",
    "employee_deleted_message": "Employee {emp_id} deleted successfully.",
    "input_error_title": "Input Error",
    "db_error_title": "Database Error",
    "employee_added_message": "Employee {name} (ID: {emp_id}) added successfully.",
    "required_fields_message": "Name, Position, Salary, and Vacation Days are required.",
    "salary_negative_error": "Salary cannot be negative.",
    "vacation_negative_error": "Vacation days cannot be negative.",
    # New keys for HRAppGUI
    "nav_employees_btn_text": "Employees",
    "nav_adv_search_btn_text": "Advanced Search",
    "nav_dashboard_btn_text": "Dashboard",
    "nav_reports_btn_text": "Reports",
    "nav_payroll_btn_text": "Payroll",
    "nav_alerts_btn_text": "Alerts",
    "nav_analytics_btn_text": "Analytics",
    "nav_user_admin_btn_text": "User Admin",
    "nav_settings_btn_text": "Settings",
    "nav_device_sync_btn_text": "Device Sync",
    "toggle_dark_mode_btn_text": "Toggle Dark Mode",
    "toggle_light_mode_btn_text": "Toggle Light Mode",
    "search_filter_frame_title": "Search & Filter",
    "search_field_label": "Field:",
    "search_term_label": "Term:",
    "search_button_text": "Search",
    "show_all_button_text": "Show All",
    "employee_list_frame_title": "Employee List",
    "employee_actions_table_frame_title": "Employee Actions (Table)",
    "selected_employee_actions_frame_title": "Selected Employee Actions",
    "view_full_profile_btn_text": "View Full Profile",
    "print_btn_text": "Print",
    "terminate_employee_btn_text": "Terminate Employee",
    "export_csv_btn_text": "Export CSV",
    "import_csv_btn_text": "Import CSV",
    "clock_in_selected_btn_text": "Clock In Selected",
    "clock_out_selected_btn_text": "Clock Out Selected",
    "view_attendance_log_btn_text": "View Attendance Log",
    "status_bar_ready_text": "Status: Ready",
    "start_date_required_error": "Start Date is required.",
    "invalid_salary_vacation_format": "Invalid format for Salary (number) or Vacation Days (integer).",
    "employee_updated_message": "Employee (ID: {emp_id}) updated successfully.",
    "no_employee_selected_error": "No employee selected or ID field is empty. Please select an employee from the list or search.",
    # About Dialog
    "about_dialog_title": "About HR Management System",
    "about_program_name_label": "Program Name:",
    "about_version_label": "Version:",
    "about_developer_label": "Developer:",
    "about_copyright_label": "Copyright:",
    "about_close_btn": "Close",
    # User Admin
    "user_admin_username_label": "Username:",
    "user_admin_password_label": "Password (leave blank to keep current):",
    "user_admin_password_hint": "(Leave blank to keep current password)",
    "user_admin_role_label": "Role:",
    "user_admin_add_btn": "Add User",
    "user_admin_save_changes_btn": "Save Changes", # Was "Update User"
    "user_admin_delete_btn": "Delete User",
    "user_admin_clear_btn": "Clear Fields",
    "user_admin_list_frame_title": "User List",
    "user_admin_details_frame_title": "User Details / Actions",
    # Employee Tasks
    "nav_employee_tasks_btn_text": "Employee Tasks",
    "tasks_view_title": "Employee Task Management",
    "tasks_filter_frame_title": "Filter Tasks",
    "tasks_assignee_label": "Assigned To (Employee):",
    "tasks_status_label": "Status:",
    "tasks_priority_label": "Priority:",
    "tasks_assigned_by_label": "Assigned By (User):",
    "tasks_monitor_label": "Monitored By (User):",
    "tasks_add_btn_text": "Add New Task",
    "tasks_edit_btn_text": "Edit Selected Task",
    "tasks_delete_btn_text": "Delete Selected Task",
    "tasks_refresh_btn_text": "Refresh List",
    "task_form_title_add": "Add New Task",
    "task_form_title_edit": "Edit Task",
    "task_title_label": "Task Title:",
    "task_description_label": "Description:",
    "task_due_date_label": "Due Date:",
    "task_all_option": "All",
    # Dashboard 2.0
    "dashboard_period_label": "Select Period:",
    "dashboard_from_date_label": "From:",
    "dashboard_to_date_label": "To:",
    "dashboard_refresh_btn_text": "Refresh Dashboard",
    "dashboard_chart_headcount_title": "Headcount by Department",
    "dashboard_chart_absenteeism_title": "Absenteeism Rate by Department (%)",
    "dashboard_chart_leave_status_title": "Leave Request Statuses",
    "dashboard_chart_dept_adherence_title": "Attendance Adherence by Department (%)",
    "dashboard_chart_payslips_title": "Payslips Generated by Department",
    "dashboard_card_employees": "Total Employees",
    "dashboard_card_pending_leaves": "Pending Leaves",
    "dashboard_card_departments": "Departments",
    "dashboard_card_absences_today": "Absences Today",
    "dashboard_card_absences_this_week": "Absences This Week",
    "dashboard_card_absences_this_month": "Absences This Month",
    "dashboard_card_absences_this_year": "Absences This Year",
    "dashboard_card_absences_last_week": "Absences Last Week",
    "dashboard_card_absences_last_month": "Absences Last Month",
    "dashboard_card_absences_last_year": "Absences Last Year",
    "dashboard_card_payslips_generated": "Payslips Generated",
    "dashboard_card_payslips_pending": "Pending Payslips",
    "dashboard_card_payslips_overdue": "Overdue Payslips",
    "dashboard_card_employee_turnover": "Employee Turnover",
    "dashboard_card_employee_turnover_rate": "Turnover Rate (%)",
    "dashboard_card_avg_working_hours": "Average Working Hours",
    "dashboard_card_avg_leave_days": "Average Leave Days",
    "dashboard_card_avg_vacation_days": "Average Vacation Days",
    "dashboard_card_avg_salary": "Average Salary",
    "dashboard_card_avg_leave_requests": "Average Leave Requests",
    "dashboard_card_avg_payslips": "Average Payslips Generated",
    "dashboard_card_avg_absences": "Average Absences",  # New key
    "dashboard_card_avg_payroll": "Average Payroll",   # New key
    "dashboard_card_avg_turnover": "Average Turnover", # New key    
    "dashboard_card_avg_working_hours": "Average Working Hours",
    "dashboard_no_data_for_charts": "No data available for charts in the selected period.",
    # Chatbot Assistant
    "nav_chatbot_btn_text": "Assistant",
    "chatbot_window_title": "HR Virtual Assistant",
    "chatbot_input_prompt": "Type your command or question...",
    "chatbot_send_btn": "Send",
    "chatbot_greeting": "Hello! How can I help you today? Type 'help' for commands.",
    "chatbot_help_text": "Available commands:\n- 'hello' or 'hi'\n- 'show employee [ID]'\n- 'list employees'\n- 'help'",
    "chatbot_unknown_command": "Sorry, I didn't understand that. Type 'help' for available commands.",
    # New keys from recent changes
    "adv_search_all_departments_option": "All Departments",
    "gender_option_all": "All Genders",
    "gender_option_male": "Male",
    "gender_option_female": "Female",
    "gender_option_other": "Other",
    "stats_summary_frame_title": "Statistics Summary",
    "recommendations_alerts_frame_title": "Recommendations & Alerts",
    "device_sync_info_frame_title": "Device Information",
    "device_sync_assoc_device_label": "Associated Device:",
    "device_sync_last_sync_label": "Last Sync:",
    "device_sync_status_label": "Status:",
    "device_sync_test_conn_btn": "Test Connection",
    # Department Management Window
    "department_management_window_title": "Department Management",
    "department_list_frame_title": "Department List",
    "dept_id_header": "ID",
    "dept_name_header": "Department Name",
    "dept_emp_count_header": "Employee Count",
    "department_details_frame_title": "Department Details",
    "dept_name_label": "Department Name:",
    "dept_description_label": "Description:",
    "dept_add_button": "Add Department",
    "dept_update_button": "Update Department",
    "dept_delete_button": "Delete Department",
    "dept_clear_button": "Clear Form",
    "dept_name_required_error": "Department name is required.", # Common error message
    "dept_add_success_message": "Department '{name}' added successfully.", # For success messages
    "dept_update_success_message": "Department '{name}' updated successfully.",

    "device_sync_resync_btn": "Resync Now",
    "device_sync_auto_sync_toggle": "Enable Auto Sync",
    "device_sync_log_frame_title": "Sync Log",
    "interview_scheduling_placeholder_label": "Manage Interview Schedules",
    "interview_scheduling_open_window_btn": "Open Interview Scheduler",
    "metrics_placeholder_label": "View HR and Application Metrics",
    "metrics_open_window_btn": "Open Metrics Dashboard",
    "metrics_dashboard_title": "HR & Application Metrics",
    "metrics_hr_tab_title": "HR Metrics",
    "metrics_app_usage_tab_title": "Application Usage",
    # Tooltips
    "tooltip_add_employee": "Open form to add a new employee (Ctrl+N).",
    "tooltip_refresh_list": "Refresh the employee list from the database.", # New key
    "tooltip_update_selected": "Update selected employee's data in the database.",
    "tooltip_clear_fields": "Clear input fields and deselect employee.",
    "tooltip_delete_selected": "Delete selected employee from the database.",
    "tooltip_view_full_profile": "Open full profile view for selected employee.",
    "tooltip_print": "Print selected employee's details.",
    "tooltip_terminate_employee": "Terminate selected employee's service.",
    "tooltip_export_csv": "Export employee data to a CSV file.",
    "tooltip_import_csv": "Import employee data from a CSV file.",
    "tooltip_clock_in_selected": "Clock in the selected employee.",
    "tooltip_clock_out_selected": "Clock out the selected employee.",
    "tooltip_view_attendance_log": "View attendance log for selected employee.",
    "tooltip_view_manage_employees": "View and manage employee details.",
    "tooltip_adv_search_employees": "Open advanced search for employees.",
    "tooltip_view_dashboard": "Open the HR dashboard.",
    "tooltip_generate_reports": "Generate various HR reports.",
    "tooltip_manage_payroll": "Access payroll management features.",
    "tooltip_view_hr_alerts": "View HR alerts and notifications.",
    "tooltip_manage_tasks": "Manage employee tasks.",
    "nav_interview_scheduling_btn_text": "Interview Scheduling", # Already present in ar.py, adding for consistency if used as tooltip key source
    "tooltip_manage_interviews": "Manage interview schedules.",
    "tooltip_access_analytics": "Access predictive analytics features.",
    "nav_metrics_btn_text": "Metrics", # Already present in ar.py, adding for consistency
    "tooltip_view_metrics": "View HR and application metrics.",
    "tooltip_sync_device_data": "Synchronize data with attendance devices.",
    "tooltip_manage_users": "Manage application users and roles.",
    "tooltip_configure_settings": "Configure application settings.",
    "tooltip_open_chatbot": "Open the HR virtual assistant.",
    "tooltip_show_about_program": "Show information about the program.",
    "tooltip_toggle_theme": "Toggle between light and dark themes.",
    # UI elements that need translation
    "main_tab_employees": "Employees",
    "main_tab_search": "Search",
        # "main_tab_dashboard": "Dashboard", # Removed
        # "main_tab_reports": "Reports", # Removed
        # "main_tab_payroll": "Payroll", # Removed
    "main_tab_alerts": "Alerts",
    "main_tab_analytics": "Analytics",
    "# main_tab_user_admin": "User Admin",
     # "main_tab_settings": "Settings", # Removed
    "main_tab_device_sync": "Device Sync",
    "main_tab_tasks": "Tasks",
    "main_tab_metrics": "Metrics",
    "main_tab_interview_scheduling": "Interview Scheduling",
    "emp_details_tab_general_info": "General Info", # This line is correct
    "emp_details_tab_attendance": "Attendance",
    "emp_details_tab_payroll": "Payroll History",
    "emp_details_tab_documents": "Documents",
    "emp_details_tab_action_log": "Action Log",
    "job_details_section_title": "Job Details",
    "benefits_device_section_title": "Benefits & Device",
    "qualifications_history_section_title": "Qualifications & History",
    "emp_hist_section_title": "📜 Employment History",
    "photo_section_title": "🖼️ Photo",
    "no_photo_text": "No Photo",
    "marital_status_icon_label": "🎂 Marital Status:",
    "gender_icon_label": "🚻 Gender:",
    "phone_icon_label": "☎ Phone:",
    "email_icon_label": "📧 Email:",
        "department_icon_label": "🏢 Department:", "position_icon_label": "💼 Position:",
    "salary_icon_label": "💰 Salary:",
    "start_date_icon_label": "📅 Start Date:",
    "status_icon_label": "🚦 Status:",
    "termination_date_icon_label": "🚪 Termination Date:",
    "vacation_days_icon_label": "🏖️ Vacation Days:",
    "exclude_vacation_policy_icon_label": "🚫 Exclude Vacation Policy:",
    "device_user_id_icon_label": "🆔 Device User ID:",
    "education_icon_label": "🎓 Education:",
    "dashboard_placeholder_label": "Dashboard content will be displayed here. Click button to open full dashboard.",
    "reports_placeholder_label": "Reports content will be displayed here. Click button to open reports window.",
    "payroll_placeholder_label": "Payroll content will be displayed here. Click button to open payroll window.",
    "alerts_placeholder_label": "Alerts content will be displayed here. Click button to open alerts window.",
    "settings_placeholder_label": "Settings content will be displayed here. Click button to open settings window.",
    "analytics_placeholder_title": "Predictive Analytics (Experimental)",
    "analytics_train_attrition_btn": "Train Employee Attrition Model",
    "analytics_attrition_placeholder_text": "Attrition model status and predictions will appear here...",
    "profile_window_title_prefix": "Profile",
    "profile_tab_details": "Personal & Employment Details",
    "profile_tab_documents": "Documents",
    "profile_tab_action_log": "Action Log",
    "profile_tab_econtract": "Electronic Contract",
    "profile_tab_cv_analysis": "CV Analysis & Suitability",
    "profile_section_personal_info": "👤 Personal Information",
    "profile_section_contact_info": "📞 Contact Information",
    "profile_section_employment_details": "💼 Employment Details",
    "profile_section_system_benefits": "⚙️ System & Benefits",
    "profile_section_qualifications": "🎓 Qualifications",
    "profile_section_photo": "🖼️ Photo",
    "profile_no_photo_text": "No Photo Available",
    "profile_section_emp_history": "📜 Employment History",
    "profile_doc_section_title": "Documents",
    "profile_doc_view_btn": "View Selected",
    "profile_doc_delete_btn": "Delete Selected",
    "profile_doc_add_btn": "Add Document",
    "profile_doc_sign_btn": "Sign Document",
    "profile_doc_create_contract_btn": "Create New Contract",
    "profile_doc_id_header": "Doc ID",
    "profile_doc_type_header": "Type",
    "profile_doc_filename_header": "Filename",
    "profile_doc_uploaded_header": "Uploaded On",
    "profile_action_log_timestamp_header": "Timestamp",
    "profile_action_log_section_title": "Employee Action History",
    "profile_action_log_action_header": "Action Description",
    "profile_window_title": "{name}'s Profile",
    "profile_tab_action_log": "Action Log",
    "system_unknown_user": "System/Unknown",
    "profile_action_log_performed_by_header": "Performed By",
    "profile_econtract_section_title": "Manage Electronic Contracts for this Employee",
    "profile_econtract_manage_btn": "Create/Manage Contracts",
    "profile_cv_upload_section_title": "Upload & Parse Resume",
    "profile_cv_file_label": "Resume File:",
    "profile_cv_browse_btn": "Browse...",
    "profile_cv_parse_btn": "Parse Resume",
    "profile_cv_extracted_data_section_title": "Extracted Resume Data",
    "profile_cv_parsed_data_placeholder": "Parsed resume data will appear here...",
    "profile_cv_suitability_section_title": "Basic Suitability Assessment",
    "profile_cv_job_desc_label": "Job Description/Keywords:",
    "profile_cv_job_desc_placeholder": "Paste job description or required skills keywords here (comma-separated for keywords).",
    "profile_cv_assess_btn": "Assess Suitability",
    "profile_cv_suitability_results_placeholder": "Suitability assessment results will appear here...",
    "about_tech_support_header": "Technical Support",
    "about_support_email_label": "Support Email:",
    "about_support_phone_label": "Phone / WhatsApp:",
    # EmployeeFormWindow
    "form_window_title_add": "Add New Employee",
    "form_window_title_edit": "Edit Employee: {emp_id}",
    "form_section_personal_photo": "Personal & Photo",
    "form_marital_status_label": "🎂 Marital Status:", # Reuses marital_status_icon_label
    "form_gender_label": "🚻 Gender:", # Reuses gender_icon_label
    "form_photo_path_label": "🖼️ Photo Path:",
    "form_section_contact_info": "Contact Information", # Reuses profile_section_contact_info
    "form_phone_label": "☎ Phone:", # Reuses phone_icon_label
    "form_email_label": "📧 Email:", # Reuses email_icon_label
    "form_section_employment_details": "Employment Details", # Reuses profile_section_employment_details
    "form_section_benefits_device": "Benefits & Device ID", # Similar to benefits_device_section_title
    "form_vacation_days_label": "🏖️ Vacation Days:", # Reuses vacation_days_icon_label
    "form_exclude_vacation_label": "🚫 Exclude from Vacation Policy:", # Reuses exclude_vacation_policy_icon_label
    "form_device_id_label": "🆔 Device User ID:", # Reuses device_user_id_icon_label
    "form_section_qualifications_history": "Qualifications & History", # Reuses qualifications_history_section_title
    "form_education_label": "🎓 Education:", # Reuses education_icon_label
    "form_emp_history_label": "📜 Employment History:", # Reuses emp_hist_section_title
    "form_button_cancel": "Cancel",
    "form_button_clear_fields": "Clear Fields",
    "form_button_save": "Save",
    "form_photo_preview_text": "Photo Preview",
    "form_browse_btn": "Browse...", # Reuses profile_cv_browse_btn
    "form_clear_btn": "Clear", # Generic clear
    "form_tooltip_salary": "Enter the employee's gross monthly salary.",
    "form_tooltip_photo_path": "Path to the employee's photo file (JPG, PNG, etc.).",
    "form_tooltip_photo_browse": "Browse for an image file.",
    "form_tooltip_phone": "Enter employee's phone number.",
    "form_tooltip_email": "Enter employee's email address.",
    "form_tooltip_photo_clear": "Clear the selected photo path.",
    "form_tooltip_save_add": "Save the new employee record.",
    "form_tooltip_save_edit": "Save changes to the employee record.",
    "form_tooltip_clear_form": "Reset all fields in the form.",
    "form_tooltip_cancel_form": "Close this form without saving.",
    # AppSettingsWindow
    "settings_window_title": "Application Settings",
    "settings_group_cloud_backup": "☁️ Cloud Backup (Google Drive)",
    "settings_gdrive_status_label": "Status:",
    "settings_gdrive_auth_button_text": "Authenticate with Google Drive",
    "settings_gdrive_backup_now_button_text": "Backup & Sync to Drive Now",
    "settings_group_general_appearance": "⚙️ General & Appearance",
    "settings_default_lang_label": "Default Language:",
    "settings_default_theme_label": "Default Theme:",
    "settings_group_telegram": "📲 Telegram Notifications",
    "settings_telegram_token_label": "Telegram Bot Token:",
    "settings_telegram_chat_id_label": "Telegram Chat ID:",
    "settings_group_zkteco": "🔗 ZKTeco Device",
    "settings_zkteco_ip_label": "ZKTeco Device IP:",
    "settings_zkteco_port_label": "ZKTeco Device Port:",
    "settings_group_backup_recovery": "💾 Backup & Recovery",
    "settings_auto_backup_label": "Auto Backup Enabled:",
    "settings_auto_backup_freq_label": "Auto Backup Frequency:",
    "settings_group_data_management": "🧹 Data Management",
    "settings_archive_cutoff_label": "Archive Terminated Employees Before:",
    "settings_archive_button_text": "Archive Now",
    "settings_group_policies_rules": "📜 Policies & Rules",
    "settings_leave_busy_threshold_label": "Leave Busy Threshold (% Dept):",
    "settings_public_holidays_label": "Public Holidays (YYYY-MM-DD, comma-separated):",
    "settings_late_arrival_time_label": "Late Arrival Notification Time (HH:MM:SS):",
    "settings_group_auto_reports": "📊 Automated Reports",
    "settings_enable_weekly_stats_label": "Enable Weekly Stats Report:",
    "settings_report_day_label": "Report Day:",
    "settings_report_time_label": "Report Time (HH:MM):",
    "settings_button_save": "Save Settings",
    "settings_saved_title": "Settings Saved",
    "settings_saved_success_message": "Settings saved successfully.",
    "failed_to_save_settings_error": "Failed to save settings: {error}",
    "language_change_title": "Language Change",
    "settings_button_close": "Close", # Reuses about_close_btn
    # PayrollWindow
    "payroll_window_title": "Payroll Management",
    "payroll_tab_generate": "Generate Payslip",
    "payroll_tab_advances": "Salary Advances",
    "payroll_tab_rewards_penalties": "Rewards & Penalties",
    "payroll_employee_label": "Employee:",
    "payroll_period_start_label": "Period Start (YYYY-MM-DD):",
    "payroll_period_end_label": "Period End (YYYY-MM-DD):",
    "payroll_calculate_button": "Calculate Payslip",
    "payroll_payslip_details_label": "Payslip Details",
    "payroll_save_button": "Save Payslip",
    "payroll_export_pdf_button": "Export PDF",
    "payroll_rp_form_title": "Add Reward or Penalty",
    "payroll_rp_type_label": "Type:",
    "payroll_rp_reward_radio": "Reward",
    "payroll_rp_penalty_radio": "Penalty",
    "payroll_rp_description_label": "Description:",
    "payroll_rp_amount_label": "Amount:",
    "payroll_rp_eff_date_label": "Effective Date (YYYY-MM-DD):",
    "payroll_rp_add_item_button": "Add Item",
    "payroll_adv_form_title": "Add New Salary Advance",
    "payroll_adv_date_label": "Advance Date (YYYY-MM-DD):",
    "payroll_adv_amount_label": "Advance Amount:",
    "payroll_adv_repay_per_period_label": "Repayment/Period:",
    "payroll_adv_repay_start_date_label": "Repayment Start (YYYY-MM-DD):",
    "payroll_adv_add_button": "Add Salary Advance",
    # Interview Scheduling
    "interview_form_frame_title": "Schedule/Edit Interview",
    "candidate_name_label": "Candidate Name:",
    "interviewer_label": "Interviewer:",
    "date_label_format": "Date (YYYY-MM-DD):",
    "time_label_format": "Time (HH:MM):",
    "duration_minutes_label": "Duration (minutes):",
    "location_label": "Location:",
    "status_label": "Status:",
    "notes_label": "Notes:",
    "interview_schedule_button": "Schedule Interview",
    "interview_clear_form_button": "Clear Form",
    "interview_list_frame_title": "Scheduled Interviews",
    # Employee Details Tab (General Info Section Titles)
    "interview_scheduled_success_message": "Interview scheduled successfully.",
    "personal_info_section_title": "Personal Information", # Used for multiple LabelFrames
    # Placeholder button texts for opening windows from main tabs
    "dashboard_open_window_btn": "Open Full Dashboard",
    "reports_open_window_btn": "Open Reports Window",
    "payroll_open_window_btn": "Open Payroll Window",
    "alerts_open_window_btn": "Open Alerts Window",
    "settings_open_window_btn": "Open Settings Window",
    # Main Employee List Treeview Headers
    "header_emp_id": "ID",
    "header_emp_name": "Name",
    "header_emp_department": "Department",
    "header_emp_position": "Position",
    "header_emp_salary": "Salary",
    "header_emp_status": "Status",
    "header_emp_termination_date": "Termination Date",
    "header_exclude_vacation_policy": "Exclude Vacation Policy",
    # ElectronicContractWindow
    "econtract_save_signed_btn": "Save Signed Contract",
    "contract_pdf_generated_success_message": "Contract PDF generated successfully: {filepath}",
    "signing_error_title": "Signing Error",
    "create_contract_pdf_first_warning": "Please create the contract PDF first.",
    "save_error_title": "Save Error",
    "no_signed_contract_to_save_warning": "No signed contract PDF available to save. Please create and sign the contract first.",
    # ReportsWindow specific for Performance Evaluation
    "report_type_perf_eval": "Employee Performance Evaluation",
    "report_select_employee_label": "Select Employee:",
    "report_eval_period_label": "Evaluation Period (e.g., YYYY-Q[1-4] or 'Latest'):",
    "report_header_eval_period": "Eval. Period",
    "report_header_eval_date": "Eval. Date",
    "report_header_evaluator": "Evaluator",
    "report_header_criteria": "Criterion",
    "report_header_score": "Score",
    "report_header_max_points": "Max",
    "report_header_comment": "Comment",
    # Task Form
    "task_form_save_button": "Save Task",
    "unexpected_error_title": "Unexpected Error",
    "unexpected_error_occurred_message": "An unexpected error occurred: {error}",
    "report_header_overall_score": "Overall Score",
    "report_header_overall_notes": "Overall Notes",
    # Approvals Feature
    "main_tab_approvals": "Approvals",
    "nav_approvals_btn_text": "Approvals",
    "tooltip_manage_approvals": "View and manage items pending your approval.",
    "pending_approvals_frame_title": "Pending Your Approval",
    "approval_details_frame_title": "Approval Details & Actions",
    "approver_comments_label": "Approver Comments:",
    "approve_btn_text": "Approve",
    "reject_btn_text": "Reject",
    "contract_submitted_for_approval_message": "Contract submitted for approval successfully.",
    # AppSettingsWindow - GDrive
    "gdrive_status_not_authenticated": "Status: Not Authenticated. Click to authenticate.",
    "gdrive_status_authenticated": "Status: Authenticated with Google Drive.",
    "gdrive_status_auth_failed": "Status: Authentication Failed.",
    "gdrive_status_auth_error": "Status: Authentication Error.",
    "gdrive_authenticating_status": "Authenticating... Please follow browser instructions.",
    "gdrive_credentials_not_found_error": "Google API Credentials file ('{path}') not found. Cannot authenticate.",
    "gdrive_auth_failed_network_error": "Google Drive authentication failed due to a network or setup issue: {error}",
    "gdrive_auth_failed_check_logs_message": "Google Drive authentication failed. Please check logs for details.",
# DashboardWindow Charts
    "dashboard_chart_headcount_title": "Headcount by Department",
    "dashboard_chart_contract_type_title": "Contract Type Distribution",
    "dashboard_counter_total_employees": "Total Active Employees:",
    "dashboard_counter_new_this_month": "New Hires (This Month):",
    "dashboard_window_title": "HR Dashboard",
    "dashboard_tab_employees": "Employees",
    "dashboard_tab_attendance": "Attendance",
    "dashboard_tab_payroll": "Payroll",
    "dashboard_tab_performance": "Performance",
    "dashboard_charts_section_title": "Visualizations",
    # DashboardWindow Cards (from error log)
    "Total Employees": "Total Employees",
    "Pending Leaves": "Pending Leaves",
    "Departments": "Departments",
    "Absences Today": "Absences Today",
    # ReportsWindow file dialogs
    "csv_file_type_label": "CSV files",
    "all_files_type_label": "All files",
    "reports_save_csv_dialog_title": "Save Report as CSV",
    "pdf_file_type_label": "PDF files",
    "reports_save_pdf_dialog_title": "Save Report as PDF",
    # AlertsWindow messages
    "alerts_no_alerts_title": "No Alerts",
    "alerts_no_alerts_message": "No attendance alerts generated for the given criteria.",
    "reports_generation_error": "Error generating report: {error_message}",
}